- set_fact: socks_path={{ shared_path }}/sockets
  tags: always

- name: Ensure sockets directory exists
  file: path={{ socks_path }} state=directory
  tags: always

- set_fact: app_sock={{ socks_path }}/app.sock
  tags: always

- set_fact: pids_path={{ shared_path }}/pids
  tags: always

- name: Ensure pids directory exists
  file: path={{ pids_path }} state=directory
  tags: always

- set_fact: app_pid={{ pids_path }}/app.pid
  tags: always

- include: ../tasks/app_stop.yml
- include: ../tasks/app_start.yml
